# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.suhli
pluginName = datagrip-plugin-format-mongojs-prettier
pluginVersion = 2.0.0

# Supported build number ranges and IntelliJ Platform versions
pluginSinceBuild = 251
pluginUntilBuild =

# IntelliJ Platform Gradle Plugin (2.x)
platformType = IU
platformVersion = 2025.2.5

# Gradle
gradleVersion = 8.13

kotlin.stdlib.default.dependency = false
org.gradle.jvmargs = -Xmx4096m
